build_all: target based licenses and mirror handling
- create target based license archive
- collect mirror sources for later packaging
- remove mirror source packaging (done by CI later)

Signed-off-by: Martin Schmiedel <Martin.Schmiedel@tq-group.com>

diff --git a/ci/build_all b/ci/build_all
--- a/ci/build_all
+++ b/ci/build_all
@@ -427,17 +427,6 @@ main () {
 				# Should atf-imx / qoriq-atf etc. labeled as PREFERRED_PROVIDER? If yes, this should go upstream.
 				# print_virtual_provider_info "${artifactsdir}/${machine_archive}.info" "trusted-firmware-a"
 
-				# create image archive for $MACHINE, assume DEPLOY_DIR_IMAGE has ${MACHINE} as final part
-				if [ "${release}" = "yes" ]
-				then
-					if ! tar -cvf ${deploydir}/${machine_archive}.BIN.tar.gz \
-						-C "$(dirname "${artifactsdir}")" \
-						"$(basename "${artifactsdir}")" --use-compress-program=pigz
-					then
-						error_out "archiving for ${machine} failed"
-					fi
-				fi
-
 				# add some artifacts for automated testing, needed by name / pattern without
 				# bitbake timestamp annotation etc. Copy the named links as file. Real files
 				# will be copied after this.
@@ -477,7 +466,63 @@ main () {
 				# needed for test
 				find ${artifactsdir} -type f -print0 | \
 					xargs --null --no-run-if-empty cp --no-clobber --target-directory="${deploydir}/${machine}/"
-				
+
+				if [ "${release}" = "yes" ]
+				then
+					local download_dir
+					local archive_basename
+
+					archive_basename=${deploydir}/${machine_archive}
+
+					# create image archive for $MACHINE, assume DEPLOY_DIR_IMAGE has ${MACHINE} as final part
+					if ! tar -cvf "${archive_basename}.BIN.tar.gz" \
+						-C "$(dirname "${artifactsdir}")" \
+						"$(basename "${artifactsdir}")" --use-compress-program=pigz
+					then
+						error_out "archiving for ${machine} failed"
+					fi
+
+					# create licenses and mirror archive
+					mkdir -p "${archive_basename}.LIC"
+					# copy the file from licenses
+					# using LICENSE_DIRECTORY be the correct way but if we use BBMULTICONFIG
+					# there may be different values for LICENSE_DIRECTORY for one machine build
+					# this is the case for TI based SoC with k3r5
+					find . -type d -maxdepth 4 -wholename "*tmp*/deploy/licenses/*" -print0 | \
+						xargs --null --no-run-if-empty cp --recursive \
+						--target-directory="${archive_basename}.LIC/"
+
+					tar -cvf "${archive_basename}.LIC.tar.gz" \
+						--directory "$(dirname "${archive_basename}.LIC")" \
+						"$(basename "${archive_basename}.LIC")" \
+						--use-compress-program=pigz
+					# do some cleanup
+					rm -rf "${archive_basename}.LIC"
+
+					mkdir -p "${archive_basename}.MIRROR.SRC"
+					download_dir=$(bitbake-getvar -q --value DL_DIR)
+					# query all archived sources, needs archiver class in config
+					archived_src_path=$(ls -1 ./tmp*/deploy/sources/*/*/*)
+
+					# copy the file from archived sources if it exists in download_dir
+					for f in ${archived_src_path}; do
+						local filename
+						filename="${download_dir}/$(basename ${f})"
+						if [ -e "${filename}" ]; then
+							cp "${filename}" "${archive_basename}.MIRROR.SRC";
+						else
+							debug "$f has no counterpart ${filename}"
+						fi
+					done
+
+					# we assume here that bitbake is configured to use shallow cloning
+					# and that these packages use ${BITBAKE_GIT_MIRROR_PKG_EXTENSION} as extension
+					find ${download_dir} -name gitshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION} -print0 | \
+						xargs --null --no-run-if-empty cp --no-clobber --target-directory="${archive_basename}.MIRROR.SRC/"
+					find ${download_dir} -name gitsmshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION} -print0 | \
+						xargs --null --no-run-if-empty cp --no-clobber --target-directory="${archive_basename}.MIRROR.SRC/"
+
+				fi
 				# TODO: linking ${artifactsdir} to ${deploydir}/${machine} only works for fresh
 				# checkout as used in a CI environment
 			done
@@ -485,53 +530,6 @@ main () {
 
 		cd "${top_dir}"
 	done
-	if [ "${release}" = "yes" ]
-	then
-		local licenses_src_path
-		local archived_src_path
-		local download_dir
-
-		# create licenses and mirror archive
-		local archive_basename=${config}_${stamp}
-
-		mkdir -p "${archive_basename}.LIC"
-		# copy the file from licenses
-		licenses_src_path=$(ls -d ${build_dir}_*/tmp*/deploy/licenses/*)
-		for f in ${licenses_src_path}; do
-			cp -r "${f}" "${archive_basename}.LIC";
-		done
-
-		tar -cvf "${archive_basename}.LIC.tar.gz" "${archive_basename}.LIC" --use-compress-program=pigz
-		# do some cleanup
-		rm -rf "${archive_basename}.LIC"
-
-		mkdir -p "${archive_basename}.MIRROR.SRC"
-		download_dir=$(bitbake-getvar -q --value DL_DIR)
-		# query all archived sources, needs archiver class in config
-		archived_src_path=$(ls -1 ${build_dir}_*/tmp*/deploy/sources/*/*/*)
-
-		# copy the file from archived sources if it exists in download_dir
-		for f in ${archived_src_path}; do
-			local filename
-			filename="${download_dir}/$(basename ${f})"
-			if [ -e "${filename}" ]; then
-				cp "${filename}" "${archive_basename}.MIRROR.SRC";
-			else
-				debug "$f has no counterpart ${filename}"
-			fi
-		done
-
-		# we assume here that bitbake is configured to use shallow cloning
-		# and that these packages use ${BITBAKE_GIT_MIRROR_PKG_EXTENSION} as extension
-		find ${download_dir} -name gitshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION} -print0 | \
-			xargs --null --no-run-if-empty cp --target-directory="${archive_basename}.MIRROR.SRC/"
-		find ${download_dir} -name gitsmshallow_*.${BITBAKE_GIT_MIRROR_PKG_EXTENSION} -print0 | \
-			xargs --null --no-run-if-empty cp --target-directory="${archive_basename}.MIRROR.SRC/"
-
-		tar -cvf "${archive_basename}.MIRROR.SRC.tar.gz" "${archive_basename}.MIRROR.SRC" --use-compress-program=pigz
-		# do some cleanup
-		rm -rf "${archive_basename}.MIRROR.SRC"
-	fi
 }
 
 main "${@}"
