ci/build-all: backport the rewrite and error_out usage from tqma8x branch
Signed-off-by: Markus Niebel <Markus.Niebel@tq-group.com>

diff --git a/ci/build-all b/ci/build-all
--- a/ci/build-all
+++ b/ci/build-all
@@ -29,8 +29,7 @@
 readonly SCRIPTNAME="${0}"
 readonly SCRIPTPATH=$(dirname $(readlink -f "${0}"))
 
-usage()
-{
+usage() {
 	echo -e "\nUsage: ${SCRIPTNAME} <build-dir> <template> [<mode>] \n \
 	<build-dir>: specifies the build directory location (required) \n \
 	<template>: template bblayers.conf to use \n \
@@ -39,16 +38,24 @@ usage()
 	mode=ci: if given, use only mirror tarballs to build"
 }
 
+error_out () {
+	echo "ERROR: $1"
+	exit 1
+}
+
 main () {
 	# this disables network check
 	export CONNECTIVITY_CHECK_URIS=" "
 
 	local BUILD_DIR=${1}
 	local DEPLOYDIR=$(readlink -f ./${BUILD_DIR})/deployment
-	local LAYER="unknown"
-	local TARGETS="unknown"
+	local LAYER="meta-tq"
+	local ALL_TARGETS="unknown"
 	local CONFIG=${2}
-	local IMAGE=core-image-minimal
+	local IMAGES="core-image-minimal"
+	local MINIMAL_EXCLUDE=""
+	local MFGTOOL_EXCLUDE="tqma6q-nav tqmls102xa-mbls102xa"
+	local GUI_EXCLUDE=""
 	local MODE="normal"
 
 	if ! [ -z "${3}" ]
@@ -64,20 +71,40 @@ main () {
 
 	echo $1 $2 $3 $MODE
 
+	# filter out machines from the ${LAYER}
+	ALL_TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
+		sed s/\.conf//g | xargs -n1 basename)
+	local MINIMAL_TARGETS=${ALL_TARGETS}
+	local GUI_TARGETS=${ALL_TARGETS}
+	local MFGTOOL_TARGETS=${ALL_TARGETS}
+
 	case ${CONFIG} in
 	"gui" )
-		IMAGE=fsl-image-multimedia-full
-		LAYER="meta-tq"
+		IMAGES="fsl-image-multimedia-full"
+		# tqma6q-nav and tqmls102xa-mbls102xa have no support for mfgtool
+		for excl in ${GUI_EXCLUDE}; do
+			GUI_TARGETS=$(echo ${GUI_TARGETS} | sed -e "s/ *$excl */ /")
+		done
+		export MACHINE=$(echo $GUI_TARGETS | awk '{ print $1 }')
+		ALL_TARGETS=${GUI_TARGETS}
 		export EULA="y"
 		;;
 	"minimal" )
-		IMAGE=core-image-minimal
-		LAYER="meta-tq"
+		IMAGES="core-image-minimal"
+		for excl in ${MINIMAL_EXCLUDE}; do
+			MINIMAL_TARGETS=$(echo ${MINIMAL_TARGETS} | sed -e "s/ *$excl */ /")
+		done
+		export MACHINE=$(echo $MINIMAL_TARGETS | awk '{ print $1 }')
+		ALL_TARGETS=${MINIMAL_TARGETS}
 		;;
 	"mfgtool" )
-		IMAGE=fsl-image-mfgtool-initramfs
-		LAYER="meta-tq"
-		export EULA="y"
+		IMAGES="fsl-image-mfgtool-initramfs"
+		# tqma6q-nav and tqmls102xa-mbls102xa have no support for mfgtool
+		for excl in ${MFGTOOL_EXCLUDE}; do
+			MFGTOOL_TARGETS=$(echo ${MFGTOOL_TARGETS} | sed -e "s/ *$excl */ /")
+		done
+		export MACHINE=$(echo $MFGTOOL_TARGETS | awk '{ print $1 }')
+		ALL_TARGETS=${MFGTOOL_TARGETS}
 		;;
 	* )
 		usage
@@ -85,37 +112,22 @@ main () {
 		;;
 	esac
 
-	# filter out machines from the layer 
-	TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
-		sed s/\.conf//g | xargs -n1 basename)
-
-	case ${CONFIG} in
-	"gui" )
-		;;
-	"mfgtool" )
-		# tqma6q-nav and tqmls102xa-mbls102xa have no support for mfgtool
-		local EXCLUDE="tqma6q-nav tqmls102xa-mbls102xa"
-		for excl in ${EXCLUDE}; do
-			TARGETS=$(echo ${TARGETS} | sed -e "s/ *$excl */ /")
-		done
-		;;
-	* )
-		;;
-	esac
+	# filter out double entries in case we build multiple images per config
+	ALL_TARGETS=$(echo ${ALL_TARGETS} | tr ' ' '\n' | sort -u)
 
 	# source the real setup workhorse.
-	export MACHINE=$(echo $TARGETS | awk '{ print $1 }')
+	export MACHINE=$(echo ${ALL_TARGETS} | awk '{ print $1 }')
 	. ./setup-environment ${BUILD_DIR} ${CONFIG}
 	[ "$?" -ne "0" ] && echo "environment setup failed" && exit 1
 
 	if ! [ -f ./version.info ]; then
 		${SCRIPTPATH}/poky-version-check.sh mkinfo
-		[ "$?" -ne "0" ] && echo "error: failed to create version.info" && exit 1
+		[ "$?" -ne "0" ] && error_out "failed to create version.info"
 	else
 		${SCRIPTPATH}/poky-version-check.sh check
-		[ "$?" -ne "0" ] && echo "error: not clean and version changed" && exit 1
+		[ "$?" -ne "0" ] && error_out "not clean and version changed"
 	fi
-	
+
 	# modify local conf as needed before executing bitbake
 	if [ "${MODE}" == "mirror" ]; then
 		echo "build mirror"
@@ -131,24 +143,41 @@ main () {
 		echo "clean local dirs in $(pwd) ..."
 		rm -rf cache tmp sstate-cache
 		# get DL_DIR from local.conf to cleanup packages generated from git ...
-		# if there is a .done file and / or a git2_*.tar.gz ist seems the
-		# fetcher does not rerun git to update the repo
-		SETTER=$(bitbake -e -c fetchall ${IMAGE} | grep ^DL_DIR)
+		SETTER=$(bitbake -e | grep ^"DL_DIR=")
 		echo "$SETTER"
 		export ${SETTER}
+		# if there is a .done file and / or a git2_*.tar.gz it seems the
+		# fetcher does not rerun git to update the repo
 		echo "clean git2 tarballs from ${DL_DIR} ..."
 		rm -f ${DL_DIR}/git2_*.tar.gz
 		rm -f ${DL_DIR}/git2_*.tar.gz.done
 		ls -1 ${DL_DIR}/git2_*
 
-		# now force bitbake to do a fetchall for the image to generate
-		for t in $TARGETS; do
-			export MACHINE=$t
-			echo "baking: ${MACHINE} ${IMAGE} with -c fetchall"
-			bitbake -c fetchall ${IMAGE}
+		for img in ${IMAGES}; do
+			case ${img} in
+			core-image-minimal )
+				TARGETS=${MINIMAL_TARGETS}
+				;;
+			fsl-image-multimedia-full )
+				TARGETS=${GUI_TARGETS}
+				;;
+			fsl-image-mfgtool-initramfs )
+				TARGETS=${MFGTOOL_TARGETS}
+				;;
+			* )
+				;;
+			esac
+
+			# now force bitbake to do a -c fetchall for the image to generate
+			for t in $TARGETS; do
+				export MACHINE=${t}
+				echo "baking: ${MACHINE} ${img} with -c fetchall"
+				bitbake -c fetchall ${img}
+				[ "$?" -ne "0" ] && error_out "fetching ($img for $t) failed"
+			done
 		done
 
-		URL=$(bitbake -e -c fetchall ${IMAGE} | grep ^"SOURCE_MIRROR_URL=")
+		URL=$(bitbake -e | grep ^"SOURCE_MIRROR_URL=")
 		export ${URL}
 		SOURCE_MIRROR_URL=${SOURCE_MIRROR_URL#\"*}
 		SOURCE_MIRROR_URL=${SOURCE_MIRROR_URL%\"*}
@@ -171,8 +200,8 @@ main () {
 				rm -rf "${DEPLOYDIR}"
 			fi
 
-			# poky has per default precompiled native / host packages,
-			# these have malformed local URIs that prevent usage.
+			# poky has per default precompiled uninative package,
+			# this has a malformed local URI that prevent usage.
 			echo "INHERIT_remove = \"uninative\"" | tee -a conf/local.conf
 			# need to set SOURCE_MIRROR_URL in a site global config on the build server
 			# echo "SOURCE_MIRROR_URL ?= \"file:///blabla
@@ -184,16 +213,23 @@ main () {
 			echo "BB_NO_NETWORK = \"1\"" | tee -a conf/local.conf
 			# premirrors have to be configured per site ...
 
-			# cleanup: rm_work fo package work dir, RM_OLD_IMAGES for last build images
+			# cleanup: rm_work for package work dir, RM_OLD_IMAGES for last build images
 			echo "INHERIT += \"rm_work\"" | tee -a  conf/local.conf
 			echo "RM_OLD_IMAGE = \"1\""  | tee -a  conf/local.conf
+
+			echo "INHERIT += \"archiver\"" | tee -a  conf/local.conf
+			echo "COPYLEFT_LICENSE_EXCLUDE ?= \"CLOSED Proprietary\"" | tee -a  conf/local.conf
+			## echo "COPYLEFT_LICENSE_INCLUDE ?= \"*\"" | tee -a  conf/local.conf
+			echo "ARCHIVER_MODE[src] ?= \"original\"" | tee -a  conf/local.conf
+			## echo "COPYLEFT_RECIPE_TYPES ?= \"\${COPYLEFT_AVAILABLE_RECIPE_TYPES}\"" | tee -a  conf/local.conf
+			## echo "COPYLEFT_RECIPE_TYPE ?= \"\${COPYLEFT_AVAILABLE_RECIPE_TYPES}\"" | tee -a  conf/local.conf
 		fi
 
 		if ! [ -z ${SSTATE_DIR} ]; then
 			# add SSTATE dir outside of builddir, optimize global builds
 			echo "SSTATE_DIR = \"${SSTATE_DIR}\"" | tee -a conf/local.conf
 		else
-			echo "SSTATE_DIR empty"
+			echo "env SSTATE_DIR empty, add it to your site.conf"
 		fi
 		if ! [ -z ${DL_DIR} ]; then
 			# add DL_DIR dir outside of builddir, optimize global builds
@@ -202,28 +238,45 @@ main () {
 			echo "DL_DIR empty"
 		fi
 
-		for t in ${TARGETS}; do
-			local err;
-			# overwrite MACHINE
-			export MACHINE=${t}
-			echo "baking ${MACHINE} ${IMAGE} ..."
-			# create image for $MACHINE
-			bitbake ${IMAGE}
-			err=${?}
-			# HACKHACKHACK: fsl-image-mfgtool-initramfs needs linux-mfgtool
-			# this recipe will fail with a diagnostic error, even when
-			# building for mx6sabresd
-			# workaround: check if image exists
-			if [ "${IMAGE}" == "fsl-image-mfgtool-initramfs" ]; then
-				local THELINK="./tmp/deploy/images/${MACHINE}/${IMAGE}-${MACHINE}.cpio.gz.u-boot"
-				if [ -L ${THELINK} ] && [ -e ${THELINK} ]; then
-					echo "ok"
+		for img in ${IMAGES}; do
+			case ${img} in
+			core-image-minimal )
+				TARGETS=${MINIMAL_TARGETS}
+				;;
+			fsl-image-multimedia-full )
+				TARGETS=${GUI_TARGETS}
+				;;
+			fsl-image-mfgtool-initramfs )
+				TARGETS=${MFGTOOL_TARGETS}
+				;;
+			* )
+				;;
+			esac
+
+			# now force bitbake to generate images for all targets ...
+			for t in ${TARGETS}; do
+				local err;
+				# overwrite MACHINE
+				export MACHINE=${t}
+				echo "baking ${MACHINE} ${img} ..."
+				# create image for $MACHINE
+				bitbake ${img}
+				err=${?}
+				# HACKHACKHACK: fsl-image-mfgtool-initramfs needs linux-mfgtool
+				# this recipe will fail with a diagnostic error, even when
+				# building for mx6sabresd
+				# workaround: check if image exists
+				if [ "${img}" == "fsl-image-mfgtool-initramfs" ]; then
+					local THELINK="./tmp/deploy/images/${MACHINE}/${img}-${MACHINE}.cpio.gz.u-boot"
+					if [ -L ${THELINK} ] && [ -e ${THELINK} ]; then
+						echo "ok"
+					else
+						error_out "bitbake ${img} for ${MACHINE} failed, no ${THELINK}"
+					fi
 				else
-					echo "bitbake ${IMAGE} for ${MACHINE} failed, no ${THELINK}" && exit 1
+					[ "${err}" -ne "0" ] && error_out "bitbake ${img} for ${MACHINE} failed"
 				fi
-			else
-				[ "${err}" -ne "0" ] && echo "bitbake ${IMAGE} for ${MACHINE} failed" && exit 1
-			fi
+			done
 		done
 
 		if [ "${MODE}" == "ci" ]; then
@@ -235,15 +288,16 @@ main () {
 			export ${VERSION}
 			DISTRO_VERSION=${DISTRO_VERSION#\"*}
 			DISTRO_VERSION=${DISTRO_VERSION%\"*}
+			TARGETS=${MINIMAL_TARGETS}
 
-			for t in ${TARGETS}; do
+			for t in ${ALL_TARGETS}; do
 				MACHINE=${t}
-				echo "archiving ${MACHINE} ${IMAGE} ..."
+				echo "archiving ${MACHINE} ..."
 				# create a file containing the version we are build from
 				git log -1 > ${ARTIFACTSDIR}/${MACHINE}/${STAMP}.info;
 				# create image archive for $MACHINE
-				tar -cvzf ${DEPLOYDIR}/${MACHINE}-${IMAGE}-yocto-${DISTRO_VERSION}-${STAMP}.tar.gz -C ${ARTIFACTSDIR} ${MACHINE}
-				[ "$?" -ne "0" ] && echo "archiving for ${MACHINE} failed" && exit 1
+				tar -cvzf ${DEPLOYDIR}/${MACHINE}-${CONFIG}-yocto-${DISTRO_VERSION}-${STAMP}.tar.gz -C ${ARTIFACTSDIR} ${MACHINE}
+				[ "$?" -ne "0" ] && error_out "archiving for ${MACHINE} failed"
 			done
 		fi
 	fi
