ci: build-all: adapt to current used bsp setup
- no plain OE support
- use fsl bsp setup script
- build core-image-minimal, fsl-image-multimedia and mfgtool from one buildspace
- force to use fsl wayland distro

Signed-off-by: Markus Niebel <Markus.Niebel@tq-group.com>
(cherry picked from commit cd0aa9238d90ebf3a137ba415e2e589626df37ed)
Signed-off-by: Markus Niebel <Markus.Niebel@tq-group.com>

diff --git a/ci/build-all b/ci/build-all
--- a/ci/build-all
+++ b/ci/build-all
@@ -29,14 +29,18 @@
 readonly SCRIPTNAME="${0}"
 readonly SCRIPTPATH=$(dirname $(readlink -f "${0}"))
 
-usage()
-{
+usage() {
 	echo -e "\nUsage: ${SCRIPTNAME} <build-dir> <template> [<mode>] \n \
 	<build-dir>: specifies the build directory location (required) \n \
 	<template>: template bblayers.conf to use \n \
 	mode=normal or not given: do normal build \n
 	mode=mirror: if given, download only and provide mirror tarballs \n
 	mode=ci: if given, use only mirror tarballs to build"
+}
+
+error_out () {
+	echo "ERROR: $1"
+	exit 1
 }
 
 main () {
@@ -48,7 +52,7 @@ main () {
 	local LAYER="unknown"
 	local TARGETS="unknown"
 	local CONFIG=${2}
-	local IMAGE=core-image-minimal
+	local DEFAULT_IMAGE=core-image-minimal
 	local MODE="normal"
 
 	if ! [ -z "${3}" ]
@@ -66,16 +70,18 @@ main () {
 
 	case ${CONFIG} in
 	"gui" )
-		IMAGE=fsl-image-multimedia-full
+		IMAGES="core-image-minimal fsl-image-multimedia fsl-image-mfgtool-initramfs"
 		LAYER="meta-tq"
 		export EULA="y"
 		;;
 	"minimal" )
-		IMAGE=core-image-minimal
+		IMAGES=${DEFAULT_IMAGE}
+		# TODO: remove when building without meta-freescale is possible
+		export EULA="y"
 		LAYER="meta-tq"
 		;;
 	"mfgtool" )
-		IMAGE=fsl-image-mfgtool-initramfs
+		IMAGES=fsl-image-mfgtool-initramfs
 		LAYER="meta-tq"
 		export EULA="y"
 		;;
@@ -86,18 +92,25 @@ main () {
 	esac
 
 	# filter out machines from the layer 
-	TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
-		sed s/\.conf//g | xargs -n1 basename)
+	#TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
+	#	sed s/\.conf//g | xargs -n1 basename)
+	# TODO: find real boards to be build ...
+	TARGETS=imx8qxpmek
 
 	case ${CONFIG} in
 	"gui" )
+		# tqmls102xa-mbls102xa qspi is to small for large multimedia image
+		# local EXCLUDE="tqmls102xa-mbls102xa"
+		# for excl in ${EXCLUDE}; do
+		#	TARGETS=$(echo ${TARGETS} | sed -e "s/ *$excl */ /")
+		#done
 		;;
 	"mfgtool" )
 		# tqma6q-nav and tqmls102xa-mbls102xa have no support for mfgtool
-		local EXCLUDE="tqma6q-nav tqmls102xa-mbls102xa"
-		for excl in ${EXCLUDE}; do
-			TARGETS=$(echo ${TARGETS} | sed -e "s/ *$excl */ /")
-		done
+		#local EXCLUDE="tqma6q-nav tqmls102xa-mbls102xa"
+		#for excl in ${EXCLUDE}; do
+		#	TARGETS=$(echo ${TARGETS} | sed -e "s/ *$excl */ /")
+		#done
 		;;
 	* )
 		;;
@@ -105,15 +118,17 @@ main () {
 
 	# source the real setup workhorse.
 	export MACHINE=$(echo $TARGETS | awk '{ print $1 }')
-	. ./setup-environment ${BUILD_DIR} ${CONFIG}
+	# TODO: need to call nxp setup script ...
+	#. ./setup-environment ${BUILD_DIR} ${CONFIG}
+	. ./fsl-setup-release.sh -b ${BUILD_DIR} -e wayland
 	[ "$?" -ne "0" ] && echo "environment setup failed" && exit 1
 
 	if ! [ -f ./version.info ]; then
 		${SCRIPTPATH}/poky-version-check.sh mkinfo
-		[ "$?" -ne "0" ] && echo "error: failed to create version.info" && exit 1
+		[ "$?" -ne "0" ] && error_out "failed to create version.info"
 	else
 		${SCRIPTPATH}/poky-version-check.sh check
-		[ "$?" -ne "0" ] && echo "error: not clean and version changed" && exit 1
+		[ "$?" -ne "0" ] && error_out "not clean and version changed"
 	fi
 	
 	# modify local conf as needed before executing bitbake
@@ -131,11 +146,11 @@ main () {
 		echo "clean local dirs in $(pwd) ..."
 		rm -rf cache tmp sstate-cache
 		# get DL_DIR from local.conf to cleanup packages generated from git ...
-		# if there is a .done file and / or a git2_*.tar.gz ist seems the
-		# fetcher does not rerun git to update the repo
-		SETTER=$(bitbake -e -c fetchall ${IMAGE} | grep ^DL_DIR)
+		SETTER=$(bitbake -e -c fetchall ${DEFAULT_IMAGE} | grep ^DL_DIR)
 		echo "$SETTER"
 		export ${SETTER}
+		# if there is a .done file and / or a git2_*.tar.gz it seems the
+		# fetcher does not rerun git to update the repo
 		echo "clean git2 tarballs from ${DL_DIR} ..."
 		rm -f ${DL_DIR}/git2_*.tar.gz
 		rm -f ${DL_DIR}/git2_*.tar.gz.done
@@ -144,11 +159,17 @@ main () {
 		# now force bitbake to do a fetchall for the image to generate
 		for t in $TARGETS; do
 			export MACHINE=$t
-			echo "baking: ${MACHINE} ${IMAGE} with -c fetchall"
-			bitbake -c fetchall ${IMAGE}
+
+			for img in ${IMAGES}; do
+				echo "baking: ${MACHINE} ${img} with -c fetchall"
+				bitbake -c fetchall ${img}
+				[ "$?" -ne "0" ] && error_out "fetching ($img for $t) failed"
+			done
+
 		done
 
-		URL=$(bitbake -e -c fetchall ${IMAGE} | grep ^SOURCE_MIRROR_URL)
+		URL=$(bitbake -e -c fetchall ${DEFAULT_IMAGE} | grep ^SOURCE_MIRROR_URL)
+
 		export ${URL}
 		SOURCE_MIRROR_URL=${SOURCE_MIRROR_URL#\"*}
 		SOURCE_MIRROR_URL=${SOURCE_MIRROR_URL%\"*}
@@ -202,28 +223,33 @@ main () {
 			echo "DL_DIR empty"
 		fi
 
-		for t in ${TARGETS}; do
+		echo "start building $TARGETS"
+		for mach in ${TARGETS}; do
 			local err;
 			# overwrite MACHINE
-			export MACHINE=${t}
-			echo "baking ${MACHINE} ${IMAGE} ..."
-			# create image for $MACHINE
-			bitbake ${IMAGE}
-			err=${?}
-			# HACKHACKHACK: fsl-image-mfgtool-initramfs needs linux-mfgtool
-			# this recipe will fail with a diagnostic error, even when
-			# building for mx6sabresd
-			# workaround: check if image exists
-			if [ "${IMAGE}" == "fsl-image-mfgtool-initramfs" ]; then
-				local THELINK="./tmp/deploy/images/${MACHINE}/${IMAGE}-${MACHINE}.cpio.gz.u-boot"
-				if [ -L ${THELINK} ] && [ -e ${THELINK} ]; then
-					echo "ok"
+			export MACHINE=${mach}
+			echo "overwrite MACHINE: $mach -> $MACHINE"
+			echo "start building $IMAGES"
+			for img in ${IMAGES}; do
+				echo "baking ${MACHINE} ${img} ..."
+				# create image for $MACHINE
+				bitbake ${img}
+				err=${?}
+				# HACKHACKHACK: fsl-image-mfgtool-initramfs needs linux-mfgtool
+				# this recipe will fail with a diagnostic error, even when
+				# building for mx6sabresd
+				# workaround: check if image exists
+				if [ "${img}" == "fsl-image-mfgtool-initramfs" ]; then
+					local THELINK="./tmp/deploy/images/${MACHINE}/${img}-${MACHINE}.cpio.gz.u-boot"
+					if [ -L ${THELINK} ] && [ -e ${THELINK} ]; then
+						echo "ok"
+					else
+						error_out "bitbake ${img} for ${MACHINE} failed, no ${THELINK}"
+					fi
 				else
-					echo "bitbake ${IMAGE} for ${MACHINE} failed, no ${THELINK}" && exit 1
+					[ "${err}" -ne "0" ] && error_out "bitbake ${img} for ${MACHINE} failed"
 				fi
-			else
-				[ "${err}" -ne "0" ] && echo "bitbake ${IMAGE} for ${MACHINE} failed" && exit 1
-			fi
+			done
 		done
 
 		if [ "${MODE}" == "ci" ]; then
@@ -238,12 +264,12 @@ main () {
 
 			for t in ${TARGETS}; do
 				MACHINE=${t}
-				echo "archiving ${MACHINE} ${IMAGE} ..."
+				echo "archiving ${MACHINE} ..."
 				# create a file containing the version we are build from
 				git log -1 > ${ARTIFACTSDIR}/${MACHINE}/${STAMP}.info;
 				# create image archive for $MACHINE
-				tar -cvzf ${DEPLOYDIR}/${MACHINE}-${IMAGE}-yocto-${DISTRO_VERSION}-${STAMP}.tar.gz -C ${ARTIFACTSDIR} ${MACHINE}
-				[ "$?" -ne "0" ] && echo "archiving for ${MACHINE} failed" && exit 1
+				tar -cvzf deployment/${MACHINE}-yocto-${DISTRO_VERSION}-${STAMP}.tar.gz -C ${ARTIFACTSDIR} ${MACHINE}
+				[ "$?" -ne "0" ] && error_out "archiving for ${MACHINE} failed"
 			done
 		fi
 	fi
