ci/build-all: backport error handling and complete filtering
Signed-off-by: Markus Niebel <Markus.Niebel@tq-group.com>

diff --git a/ci/build-all b/ci/build-all
--- a/ci/build-all
+++ b/ci/build-all
@@ -29,14 +29,18 @@
 readonly SCRIPTNAME="${0}"
 readonly SCRIPTPATH=$(dirname $(readlink -f "${0}"))
 
-usage()
-{
+usage() {
 	echo -e "\nUsage: ${SCRIPTNAME} <build-dir> <template> [<mode>] \n \
 	<build-dir>: specifies the build directory location (required) \n \
 	<template>: template bblayers.conf to use \n \
 	mode=normal or not given: do normal build \n
 	mode=mirror: if given, download only and provide mirror tarballs \n
 	mode=ci: if given, use only mirror tarballs to build"
+}
+
+error_out () {
+	echo "ERROR: $1"
+	exit 1
 }
 
 main () {
@@ -49,6 +53,7 @@ main () {
 	local ALL_TARGETS="unknown"
 	local CONFIG=${2}
 	local IMAGES="core-image-minimal"
+	local MINIMAL_EXCLUDE=""
 	local MFGTOOL_EXCLUDE="tqma6q-nav tqmls102xa-mbls102xa"
 	local GUI_EXCLUDE=""
 	local MODE="normal"
@@ -69,6 +74,7 @@ main () {
 	# filter out machines from the ${LAYER}
 	ALL_TARGETS=$(ls sources/${LAYER}/conf/machine/*.conf | \
 		sed s/\.conf//g | xargs -n1 basename)
+	# TODO: find real boards to be build ...
 	local MINIMAL_TARGETS=${ALL_TARGETS}
 	local GUI_TARGETS=${ALL_TARGETS}
 	local MFGTOOL_TARGETS=${ALL_TARGETS}
@@ -86,6 +92,9 @@ main () {
 		;;
 	"minimal" )
 		IMAGES="core-image-minimal"
+		for excl in ${MINIMAL_EXCLUDE}; do
+			MINIMAL_TARGETS=$(echo ${MINIMAL_TARGETS} | sed -e "s/ *$excl */ /")
+		done
 		export MACHINE=$(echo $MINIMAL_TARGETS | awk '{ print $1 }')
 		ALL_TARGETS=${MINIMAL_TARGETS}
 		;;
@@ -109,15 +118,16 @@ main () {
 	ALL_TARGETS=$(echo ${ALL_TARGETS} | tr ' ' '\n' | sort -u)
 
 	# source the real setup workhorse.
+	export MACHINE=$(echo ${ALL_TARGETS} | awk '{ print $1 }')
 	. ./setup-environment ${BUILD_DIR} ${CONFIG}
 	[ "$?" -ne "0" ] && echo "environment setup failed" && exit 1
 
 	if ! [ -f ./version.info ]; then
 		${SCRIPTPATH}/poky-version-check.sh mkinfo
-		[ "$?" -ne "0" ] && echo "error: failed to create version.info" && exit 1
+		[ "$?" -ne "0" ] && error_out "failed to create version.info"
 	else
 		${SCRIPTPATH}/poky-version-check.sh check
-		[ "$?" -ne "0" ] && echo "error: not clean and version changed" && exit 1
+		[ "$?" -ne "0" ] && error_out "not clean and version changed"
 	fi
 
 	# modify local conf as needed before executing bitbake
@@ -135,12 +145,11 @@ main () {
 		echo "clean local dirs in $(pwd) ..."
 		rm -rf cache tmp sstate-cache
 		# get DL_DIR from local.conf to cleanup packages generated from git ...
-		# if there is a .done file and / or a git2_*.tar.gz ist seems the
-		# fetcher does not rerun git to update the repo
 		SETTER=$(bitbake -e | grep ^"DL_DIR=")
 		echo "$SETTER"
 		export ${SETTER}
-		# force to download to generate git tarballs for newest remote ...
+		# if there is a .done file and / or a git2_*.tar.gz it seems the
+		# fetcher does not rerun git to update the repo
 		echo "clean git2 tarballs from ${DL_DIR} ..."
 		rm -f ${DL_DIR}/git2_*.tar.gz
 		rm -f ${DL_DIR}/git2_*.tar.gz.done
@@ -161,11 +170,12 @@ main () {
 				;;
 			esac
 
-			# now force bitbake to do a fetchall for the image to generate
+			# now force bitbake to do a -c fetchall for the image to generate
 			for t in $TARGETS; do
 				export MACHINE=${t}
 				echo "baking: ${MACHINE} ${img} with -c fetchall"
 				bitbake -c fetchall ${img}
+				[ "$?" -ne "0" ] && error_out "fetching ($img for $t) failed"
 			done
 		done
 
@@ -192,8 +202,8 @@ main () {
 				rm -rf "${DEPLOYDIR}"
 			fi
 
-			# poky has per default precompiled native / host packages,
-			# these have malformed local URIs that prevent usage.
+			# poky has per default precompiled uninative package,
+			# this has a malformed local URI that prevent usage.
 			echo "INHERIT_remove = \"uninative\"" | tee -a conf/local.conf
 			# need to set SOURCE_MIRROR_URL in a site global config on the build server
 			# echo "SOURCE_MIRROR_URL ?= \"file:///blabla
@@ -205,7 +215,7 @@ main () {
 			echo "BB_NO_NETWORK = \"1\"" | tee -a conf/local.conf
 			# premirrors have to be configured per site ...
 
-			# cleanup: rm_work fo package work dir, RM_OLD_IMAGES for last build images
+			# cleanup: rm_work for package work dir, RM_OLD_IMAGES for last build images
 			echo "INHERIT += \"rm_work\"" | tee -a  conf/local.conf
 			echo "RM_OLD_IMAGE = \"1\""  | tee -a  conf/local.conf
 
@@ -221,7 +231,7 @@ main () {
 			# add SSTATE dir outside of builddir, optimize global builds
 			echo "SSTATE_DIR = \"${SSTATE_DIR}\"" | tee -a conf/local.conf
 		else
-			echo "SSTATE_DIR empty"
+			echo "env SSTATE_DIR empty, add it to your site.conf"
 		fi
 		if ! [ -z ${DL_DIR} ]; then
 			# add DL_DIR dir outside of builddir, optimize global builds
@@ -263,10 +273,10 @@ main () {
 					if [ -L ${THELINK} ] && [ -e ${THELINK} ]; then
 						echo "ok"
 					else
-						echo "bitbake ${img} for ${MACHINE} failed, no ${THELINK}" && exit 1
+						error_out "bitbake ${img} for ${MACHINE} failed, no ${THELINK}"
 					fi
 				else
-					[ "${err}" -ne "0" ] && echo "bitbake ${img} for ${MACHINE} failed" && exit 1
+					[ "${err}" -ne "0" ] && error_out "bitbake ${img} for ${MACHINE} failed"
 				fi
 			done
 		done
@@ -289,7 +299,7 @@ main () {
 				git log -1 > ${ARTIFACTSDIR}/${MACHINE}/${STAMP}.info;
 				# create image archive for $MACHINE
 				tar -cvzf ${DEPLOYDIR}/${MACHINE}-${CONFIG}-yocto-${DISTRO_VERSION}-${STAMP}.tar.gz -C ${ARTIFACTSDIR} ${MACHINE}
-				[ "$?" -ne "0" ] && echo "archiving for ${MACHINE} failed" && exit 1
+				[ "$?" -ne "0" ] && error_out "archiving for ${MACHINE} failed"
 			done
 		fi
 	fi
