ci/ls-[machines,configs,distros]: improve error handling
Fail if a command fails unhandled. Add an ERR trap handler with
output of $LINENO of error for better diagnosis.

Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>

diff --git a/ci/ls-configs b/ci/ls-configs
--- a/ci/ls-configs
+++ b/ci/ls-configs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # SPDX-License-Identifier: GPL-2.0-or-later
 #
 # Copyright (C) 2022-2023 TQ-Systems GmbH <oss@ew.tq-group.com>,
@@ -8,6 +8,16 @@
 # Description: list all configs in buildspace
 #
 ###############################################################################
+
+set -e
+set -C # noclobber
+
+
+trap 'error_abort $LINENO' ERR
+
+function error_abort () {
+	echo "error at $1"
+}
 
 readonly DEFAULT_TEMPLATEDIR="template"
 readonly DEFAULT_TEMPLATE="ci"
diff --git a/ci/ls-machines b/ci/ls-machines
--- a/ci/ls-machines
+++ b/ci/ls-machines
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # SPDX-License-Identifier: GPL-2.0-or-later
 #
 # File:        ls-machines
@@ -10,6 +10,16 @@
 # Description: list all machines in a layer
 #
 ###############################################################################
+
+set -e
+set -C # noclobber
+
+# TRAP SIGNALS
+trap 'error_abort $LINENO' ERR
+
+function error_abort () {
+	echo "error at $1"
+}
 
 readonly DEFAULT_LAYER="meta-tq/meta-tq"
 
