treewide: reflect deprecation of poky combo repo
To use separate repos instead of poky this commit contains the following
modifications:

- replace poky as submodule by separate bitbake, openembedded-core
  and meta-yocto modules
- adjust setup script to source oe-init-build-env from openembedded-core
  instead of poky
- adjust bblayer templates to new locations of meta-layers

Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>

diff --git a/ci/setup-environment b/ci/setup-environment
--- a/ci/setup-environment
+++ b/ci/setup-environment
@@ -157,9 +157,12 @@ if [ "${build_dir_setup_enabled}" = "true" ]; then
     fi
 fi
 
-OEROOT="${CWD}/sources/poky"
-if [ -e "${CWD}/sources/oe-core" ]; then
-    OEROOT="${CWD}/sources/oe-core"
+if [ -e "${CWD}/sources/openembedded-core/meta" ]; then
+    OEROOT="${CWD}/sources/openembedded-core"
+else
+    echo "ERROR: Your checkout of openembedded-core is not at the expected location." >&2
+    clean_up
+    return 1
 fi
 
 # Hide messages from oe-init-build-env.
