ci/setup_builddir: improve error handling
Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>

diff --git a/ci/setup_builddir b/ci/setup_builddir
--- a/ci/setup_builddir
+++ b/ci/setup_builddir
@@ -9,7 +9,6 @@
 #
 ###############################################################################
 
-readonly SCRIPTNAME="${0}"
 readonly SCRIPTPATH=$(dirname "$(readlink -f "${0}")")
 readonly SCRIPT="$(basename "${0}")"
 
@@ -154,7 +153,7 @@ setup_confdir() {
 	done
 	ln -s "${TEMPLATECONF}/auto.conf.normal" ./conf/auto.conf
 	if ! [ -e ./conf/auto.conf ]; then
-		echo "missing auto.conf" >&2
+		echo "${SCRIPT}: Error: missing auto.conf" >&2
 		return 1
 	fi
 
@@ -197,6 +196,10 @@ default_machine () {
 }
 
 main() {
+	if [ "${#}" -ne "1" ]; then
+		echo "${SCRIPT}: Error: no action given" >&2
+	fi
+
 	case "${1}" in
 		handle_licenses )
 			shift
@@ -215,7 +218,7 @@ main() {
 			default_machine "${@}"
 			;;
 		* ) # unsupported
-			echo "Error: Unsupported action $1" >&2
+			echo "${SCRIPT}: Error: Unsupported action $1" >&2
 			exit 1
 			;;	esac
 }
