ci/utils: validate config for get_distros_for_config and get_machines
At the moment the config parameter is not validated and
can cause a silent exit for invalid values. To make functions
reusable for commandline usage, check before use and give
an error message.

Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>

diff --git a/ci/utils b/ci/utils
--- a/ci/utils
+++ b/ci/utils
@@ -173,6 +173,18 @@ get_images () {
 }
 
 ####
+# func:   valid_config
+# brief:  check if config is in list of supported configs
+# param:  $1 - config
+####
+valid_config() {
+	local config=${1}
+	local supported_configs="$(${SCRIPTPATH}/ls-configs)"
+
+	echo ${supported_configs} | grep -wq "${config}"
+}
+
+####
 # func:   get_machines
 # brief:  return buildable machines for config
 # param:  $1 - config (imx/ls/ti/minimal)
@@ -195,6 +207,11 @@ get_machines () {
 	local imx_exclude=$(echo "${ls_machines} ${ti_machines} ${mc_machines} ${imx6ul_machines} ${imx7_machines}")
 	local ti_exclude=$(echo "${imx_machines} ${ls_machines} ${mc_machines}")
 	local choosen_machines=${all_machines}
+
+	if ! valid_config ${config}; then
+		error "invalid config: ${config}"
+		return -1
+	fi
 
 	case ${config} in
 	"imx" )
@@ -240,6 +257,11 @@ get_distros_for_config () {
 	local distro_path="sources/meta-dumpling/conf/distro"
 	local all_distros=$(cd ${distro_path} && find ./*.conf | sed -E "s/\.\/(.*)\.(.*)/\1/")
 	local chosen_distros=${all_distros}
+
+	if ! valid_config ${config}; then
+		error "invalid config: ${config}"
+		return -1
+	fi
 
 	case ${config} in
 	"imx" )
